### ISSUE TITLE
Still interested in maintaining this project?

### ISSUE THREAD

**Issue by ghost** [evant/streamqflite#1]
Hey,

I just wanted to know whether you're still interested in maintaining this project.

I had the same idea for a library like this this weekend but saw that yours is existing. The only thing missing is Dart 2 support.

If you're still interested, I would try to submit a PR where all libraries are updated and Dart 2 is supported.

**Comment by evant** [comment]
Sorry didn't have notifications on so didn't notice this till now. Merged your pr and published a new version.
