### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by droidery** [evant/streamqflite#3]
Hi @evant 

Thank you for making this library.

Just wondering when I make a query then subscribe to the stream, then I _cancel the subscription_ is the query then no longer observed for changes.

Just wanted to make sure that my SQL queries aren't accumulating and then all being watched for changes even when there are no subscribers.

**Comment by evant** [comment]
If you look at the source https://github.com/evant/streamqflite/blob/b61bf5542c313dbc9c01775353e60a91988e5178/lib/streamqflite.dart#L114 there's a single broadcast that emits what tables have changed whenever there's a table update. Everything else is built on to of that with stream opperators which I assume implement cancelation correctly. So no, nothing accumulates.
