### ISSUE TITLE
Testing - How can I mock it?

### ISSUE THREAD

**Issue by hjJunior** [evant/streamqflite#4]
First at all, thx for the amazing lib...
I would like to know how can I stub to test my functions, I'm trying to mock it but I don't know how to do it
First I wanna to test this call

```
  Stream<List<Customer>> fetchCustomers() => db.createQuery('customers')
    .mapToList(_mapCustomer);
```

I'm trying this:

```
      test("it returns a list with fake customer", () async {
        when(mockDatabase.createQuery('customers')
          .mapToList((row) => Customer.fromDB(row)))
          .thenAnswer((_) => Stream.fromIterable([fakeCustomer].cast()));

        Stream<List<Customer>> subject = CustomersCache(mockDatabase)
          .fetchCustomers();

        expect(subject, emits([fakeCustomer]));
      });
```

I think that I need to mock `createQuery` but how can I do?

**Comment by evant** [comment]
I'm curious exactly what kind of test you are trying to write where you need to mock out at that level. It should be easy to mock out `fetchCustomers()` in your example for code that needs some customers, and to test `Customer.fromDB(row)` by passing in a map.

**Comment by hjJunior** [comment]
Well, the objective is do unit test, and I'm trying to assert with my function `fetchCustomers()` returns a Stream that emits a data.
I'm not sure but to do this using Sqflite I was supposed to mock the result of the query

This code bellow its was they way I used to do with Sqflite
```
when(mockDatabase.query("customers"))
  .thenAnswer((_) => Future.value([fakeCustomer.mapToDatabase]));

List<Customer> subject = await CustomersCache(mockDatabase)
  .fetchCustomers();

expect(subject.first.id, fakeCustomer.id);
```

**Comment by evant** [comment]
Ok I see, so you'll need to do
```
        when(mockDatabase.createQuery('customers')
          .thenAnswer((_) => ...);
```
and have it return a QueryStream. You can look at the source to see how to create one. A helper might be useful for testing.

**Comment by hjJunior** [comment]
I got it, I was thinking to mock Streamqflite instead of database 
thx.
