### ISSUE TITLE
Provide generic map function

### ISSUE THREAD

**Issue by droidery** [evant/streamqflite#5]
Is there a generic map function I can use with this library?

My app uses BuiltList<T> instead of List<T> so I want to do something like this

```
  Stream<BuiltList<T>> mapToBuiltList<T>(T mapper(Map<String, dynamic> row)) {
    return _source.asyncMap((query) => query()).map((rows) {
      var result = BuiltList<T>().toBuilder();

      for (final row in rows) {
        result.add(mapper(row));
      }

      return result.build();
    });
  }
```

I think the library should expose a generic map function so that any data structure can be used.

`_source.asyncMap((query) => query())` is the part that could be exposed.

**Comment by evant** [comment]
`QueryStream` extends `Stream` so you can already asyncMap on it. But yeah some kind of function like `mapTo(collector, mapper)` would be useful as you could reuse the same collector everywhere.

**Comment by droidery** [comment]
Thanks somehow missed that

**Comment by evant** [comment]
Planning on adding a [collector interface](https://github.com/evant/streamqflite/pull/7), you can use it with `BuiltList` like so:

```dart
class BuiltListCollector<T>
    implements Collector<T, ListBuilder<T>, BuiltList<T>> {
  const BuiltListCollector();

  @override
  ListBuilder<T> supply(int length) => ListBuilder();

  @override
  void add(ListBuilder<T> accumulator, int index, T element) {
    accumulator.add(element);
  }

  @override
  BuiltList<T> finish(ListBuilder<T> accumulator) => accumulator.build();
}

streamDb.createQuery("MyTable", where: 'name LIKE ?', whereArgs: [query])
    .mapTo(BuiltListCollector(), (row) => MyEntry(row));
```


Thoughts?

**Comment by droidery** [comment]
Neat! Maybe you could also solve this by passing in a fold function instead of a map function then the client doesn't need the collector interface and  you can fold into a list, BuiltList builder or single value.

**Comment by evant** [comment]
Now that dart has [extension methods](https://dart.dev/guides/language/extension-methods), don't think something like this is very useful, you can do:

```dart
extension BuiltListExtension on Stream<LazyQuery> {
  Stream<BuiltList<T>> mapToBuiltList<T>(T mapper(Map<String, dynamic> row)) {
    return this.asyncMap((query) => query()).map((rows) {
      var result = BuiltList<T>().toBuilder();

      for (final row in rows) {
        result.add(mapper(row));
      }

      return result.build();
    });
  }
}
```
